// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const compareAndSwapPasswordHash = `-- name: CompareAndSwapPasswordHash :execrows
UPDATE app.password_credentials SET password_hash = $1, updated_at = $2
WHERE user_id = $3 AND password_hash = $4
`

type CompareAndSwapPasswordHashParams struct {
	NewHash string
	Now     pgtype.Timestamptz
	UserID  pgtype.UUID
	OldHash string
}

func (q *Queries) CompareAndSwapPasswordHash(ctx context.Context, arg CompareAndSwapPasswordHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, compareAndSwapPasswordHash,
		arg.NewHash,
		arg.Now,
		arg.UserID,
		arg.OldHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createEmailIdentity = `-- name: CreateEmailIdentity :exec
INSERT INTO app.auth_identities (id, user_id, provider, provider_subject, email, created_at, updated_at)
VALUES ($1, $2, 'email', $3::text, $3::text, $4, $4)
`

type CreateEmailIdentityParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	Email  string
	Now    pgtype.Timestamptz
}

func (q *Queries) CreateEmailIdentity(ctx context.Context, arg CreateEmailIdentityParams) error {
	_, err := q.db.Exec(ctx, createEmailIdentity,
		arg.ID,
		arg.UserID,
		arg.Email,
		arg.Now,
	)
	return err
}

const createPasswordCredential = `-- name: CreatePasswordCredential :exec
INSERT INTO app.password_credentials (user_id, password_hash, password_updated_at, created_at, updated_at)
VALUES ($1, $2, $3, $3, $3)
`

type CreatePasswordCredentialParams struct {
	UserID            pgtype.UUID
	PasswordHash      string
	PasswordUpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreatePasswordCredential(ctx context.Context, arg CreatePasswordCredentialParams) error {
	_, err := q.db.Exec(ctx, createPasswordCredential, arg.UserID, arg.PasswordHash, arg.PasswordUpdatedAt)
	return err
}

const findLocalCredentialByEmailSubject = `-- name: FindLocalCredentialByEmailSubject :one
SELECT u.id, u.account_state, u.deleted_at, c.password_hash
FROM app.auth_identities a JOIN app.users u ON u.id = a.user_id
JOIN app.password_credentials c ON c.user_id = u.id
WHERE a.provider = 'email' AND a.provider_subject = $1
`

type FindLocalCredentialByEmailSubjectRow struct {
	ID           pgtype.UUID
	AccountState string
	DeletedAt    pgtype.Timestamptz
	PasswordHash string
}

func (q *Queries) FindLocalCredentialByEmailSubject(ctx context.Context, providerSubject string) (FindLocalCredentialByEmailSubjectRow, error) {
	row := q.db.QueryRow(ctx, findLocalCredentialByEmailSubject, providerSubject)
	var i FindLocalCredentialByEmailSubjectRow
	err := row.Scan(
		&i.ID,
		&i.AccountState,
		&i.DeletedAt,
		&i.PasswordHash,
	)
	return i, err
}
