// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package sqlc

import (
	"context"
)

const checkReadiness = `-- name: CheckReadiness :one
SELECT 1::integer AS ready
`

func (q *Queries) CheckReadiness(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, checkReadiness)
	var ready int32
	err := row.Scan(&ready)
	return ready, err
}
