// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :exec
INSERT INTO app.user_profiles (user_id, created_at, updated_at) VALUES ($1, $2, $2)
`

type CreateProfileParams struct {
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) error {
	_, err := q.db.Exec(ctx, createProfile, arg.UserID, arg.CreatedAt)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO app.users (id, created_at, updated_at) VALUES ($1, $2, $2)
`

type CreateUserParams struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.ID, arg.CreatedAt)
	return err
}

const getMe = `-- name: GetMe :one
SELECT u.id, u.account_state, u.created_at, p.handle, p.display_name, p.bio,
       p.search_engine_indexing, a.email, a.verified_at
FROM app.users u JOIN app.user_profiles p ON p.user_id = u.id
JOIN app.auth_identities a ON a.user_id = u.id AND a.provider = 'email'
WHERE u.id = $1 AND u.account_state = 'active' AND u.deleted_at IS NULL
`

type GetMeRow struct {
	ID                   pgtype.UUID
	AccountState         string
	CreatedAt            pgtype.Timestamptz
	Handle               pgtype.Text
	DisplayName          pgtype.Text
	Bio                  pgtype.Text
	SearchEngineIndexing bool
	Email                pgtype.Text
	VerifiedAt           pgtype.Timestamptz
}

func (q *Queries) GetMe(ctx context.Context, id pgtype.UUID) (GetMeRow, error) {
	row := q.db.QueryRow(ctx, getMe, id)
	var i GetMeRow
	err := row.Scan(
		&i.ID,
		&i.AccountState,
		&i.CreatedAt,
		&i.Handle,
		&i.DisplayName,
		&i.Bio,
		&i.SearchEngineIndexing,
		&i.Email,
		&i.VerifiedAt,
	)
	return i, err
}

const getPublicProfileByHandle = `-- name: GetPublicProfileByHandle :one
SELECT p.handle, p.display_name, p.bio
FROM app.user_profiles p JOIN app.users u ON u.id = p.user_id
WHERE p.handle = $1 AND u.account_state = 'active' AND u.deleted_at IS NULL
`

type GetPublicProfileByHandleRow struct {
	Handle      pgtype.Text
	DisplayName pgtype.Text
	Bio         pgtype.Text
}

func (q *Queries) GetPublicProfileByHandle(ctx context.Context, handle pgtype.Text) (GetPublicProfileByHandleRow, error) {
	row := q.db.QueryRow(ctx, getPublicProfileByHandle, handle)
	var i GetPublicProfileByHandleRow
	err := row.Scan(&i.Handle, &i.DisplayName, &i.Bio)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :execrows
UPDATE app.user_profiles p SET
    handle = CASE WHEN $1::boolean THEN $2::text ELSE p.handle END,
    display_name = CASE WHEN $3::boolean THEN $4::text ELSE p.display_name END,
    bio = CASE WHEN $5::boolean THEN $6::text ELSE p.bio END,
    search_engine_indexing = CASE WHEN $7::boolean THEN $8::boolean ELSE p.search_engine_indexing END,
    updated_at = $9::timestamptz
WHERE p.user_id = $10 AND EXISTS (
    SELECT 1 FROM app.users u WHERE u.id = p.user_id AND u.account_state = 'active' AND u.deleted_at IS NULL
)
`

type UpdateProfileParams struct {
	SetHandle            bool
	Handle               pgtype.Text
	SetDisplayName       bool
	DisplayName          pgtype.Text
	SetBio               bool
	Bio                  pgtype.Text
	SetIndexing          bool
	SearchEngineIndexing bool
	Now                  pgtype.Timestamptz
	UserID               pgtype.UUID
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProfile,
		arg.SetHandle,
		arg.Handle,
		arg.SetDisplayName,
		arg.DisplayName,
		arg.SetBio,
		arg.Bio,
		arg.SetIndexing,
		arg.SearchEngineIndexing,
		arg.Now,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
