// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailIdentityForOAuthAccount = `-- name: CreateEmailIdentityForOAuthAccount :exec
INSERT INTO app.auth_identities(id,user_id,provider,provider_subject,email,verified_at,created_at,updated_at)
VALUES ($1,$2,'email',$3::text,$3::text,$4,$5,$5)
`

type CreateEmailIdentityForOAuthAccountParams struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Email      string
	VerifiedAt pgtype.Timestamptz
	Now        pgtype.Timestamptz
}

func (q *Queries) CreateEmailIdentityForOAuthAccount(ctx context.Context, arg CreateEmailIdentityForOAuthAccountParams) error {
	_, err := q.db.Exec(ctx, createEmailIdentityForOAuthAccount,
		arg.ID,
		arg.UserID,
		arg.Email,
		arg.VerifiedAt,
		arg.Now,
	)
	return err
}

const createProviderIdentity = `-- name: CreateProviderIdentity :exec
INSERT INTO app.auth_identities(id,user_id,provider,provider_subject,email,verified_at,created_at,updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$7)
`

type CreateProviderIdentityParams struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Provider        string
	ProviderSubject string
	Email           pgtype.Text
	VerifiedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateProviderIdentity(ctx context.Context, arg CreateProviderIdentityParams) error {
	_, err := q.db.Exec(ctx, createProviderIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderSubject,
		arg.Email,
		arg.VerifiedAt,
		arg.CreatedAt,
	)
	return err
}

const deleteProviderIdentity = `-- name: DeleteProviderIdentity :execrows
DELETE FROM app.auth_identities WHERE user_id=$1 AND provider=$2 AND provider IN ('google','github')
`

type DeleteProviderIdentityParams struct {
	UserID   pgtype.UUID
	Provider string
}

func (q *Queries) DeleteProviderIdentity(ctx context.Context, arg DeleteProviderIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProviderIdentity, arg.UserID, arg.Provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findEmailIdentityBySubject = `-- name: FindEmailIdentityBySubject :one
SELECT user_id FROM app.auth_identities WHERE provider='email' AND provider_subject=$1
`

func (q *Queries) FindEmailIdentityBySubject(ctx context.Context, providerSubject string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findEmailIdentityBySubject, providerSubject)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const findProviderIdentity = `-- name: FindProviderIdentity :one
SELECT id, user_id, provider, provider_subject, email, created_at FROM app.auth_identities
WHERE provider=$1 AND provider_subject=$2 AND provider IN ('google','github')
`

type FindProviderIdentityParams struct {
	Provider string
	Subject  string
}

type FindProviderIdentityRow struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Provider        string
	ProviderSubject string
	Email           pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) FindProviderIdentity(ctx context.Context, arg FindProviderIdentityParams) (FindProviderIdentityRow, error) {
	row := q.db.QueryRow(ctx, findProviderIdentity, arg.Provider, arg.Subject)
	var i FindProviderIdentityRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const findProviderIdentityForUpdate = `-- name: FindProviderIdentityForUpdate :one
SELECT id, user_id, provider, provider_subject, email, created_at FROM app.auth_identities
WHERE provider=$1 AND provider_subject=$2 AND provider IN ('google','github') FOR UPDATE
`

type FindProviderIdentityForUpdateParams struct {
	Provider string
	Subject  string
}

type FindProviderIdentityForUpdateRow struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Provider        string
	ProviderSubject string
	Email           pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) FindProviderIdentityForUpdate(ctx context.Context, arg FindProviderIdentityForUpdateParams) (FindProviderIdentityForUpdateRow, error) {
	row := q.db.QueryRow(ctx, findProviderIdentityForUpdate, arg.Provider, arg.Subject)
	var i FindProviderIdentityForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordChangeTime = `-- name: GetPasswordChangeTime :one
SELECT password_updated_at FROM app.password_credentials WHERE user_id=$1
`

func (q *Queries) GetPasswordChangeTime(ctx context.Context, userID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getPasswordChangeTime, userID)
	var password_updated_at pgtype.Timestamptz
	err := row.Scan(&password_updated_at)
	return password_updated_at, err
}

const hasPasswordCredential = `-- name: HasPasswordCredential :one
SELECT EXISTS(SELECT 1 FROM app.password_credentials WHERE user_id=$1)
`

func (q *Queries) HasPasswordCredential(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasPasswordCredential, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const initializeOAuthProfile = `-- name: InitializeOAuthProfile :exec
UPDATE app.user_profiles SET display_name=$2 WHERE user_id=$1
`

type InitializeOAuthProfileParams struct {
	UserID      pgtype.UUID
	DisplayName pgtype.Text
}

func (q *Queries) InitializeOAuthProfile(ctx context.Context, arg InitializeOAuthProfileParams) error {
	_, err := q.db.Exec(ctx, initializeOAuthProfile, arg.UserID, arg.DisplayName)
	return err
}

const listProviderIdentitiesForUser = `-- name: ListProviderIdentitiesForUser :many
SELECT id, provider, provider_subject, email, created_at FROM app.auth_identities
WHERE user_id=$1 AND provider IN ('google','github') ORDER BY provider
`

type ListProviderIdentitiesForUserRow struct {
	ID              pgtype.UUID
	Provider        string
	ProviderSubject string
	Email           pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) ListProviderIdentitiesForUser(ctx context.Context, userID pgtype.UUID) ([]ListProviderIdentitiesForUserRow, error) {
	rows, err := q.db.Query(ctx, listProviderIdentitiesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProviderIdentitiesForUserRow{}
	for rows.Next() {
		var i ListProviderIdentitiesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ProviderSubject,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserAuthState = `-- name: LockUserAuthState :one
SELECT id FROM app.users WHERE id=$1 AND account_state='active' AND deleted_at IS NULL FOR UPDATE
`

func (q *Queries) LockUserAuthState(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockUserAuthState, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const revokeSessionsByAuthMethod = `-- name: RevokeSessionsByAuthMethod :exec
UPDATE app.sessions SET revoked_at=$1
WHERE user_id=$2 AND kind='public' AND auth_method=$3 AND revoked_at IS NULL
`

type RevokeSessionsByAuthMethodParams struct {
	Now        pgtype.Timestamptz
	UserID     pgtype.UUID
	AuthMethod string
}

func (q *Queries) RevokeSessionsByAuthMethod(ctx context.Context, arg RevokeSessionsByAuthMethodParams) error {
	_, err := q.db.Exec(ctx, revokeSessionsByAuthMethod, arg.Now, arg.UserID, arg.AuthMethod)
	return err
}

const updateProviderIdentityMetadata = `-- name: UpdateProviderIdentityMetadata :exec
UPDATE app.auth_identities SET email=$1,updated_at=$2
WHERE id=$3 AND user_id=$4 AND provider IN ('google','github')
`

type UpdateProviderIdentityMetadataParams struct {
	Email  pgtype.Text
	Now    pgtype.Timestamptz
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) UpdateProviderIdentityMetadata(ctx context.Context, arg UpdateProviderIdentityMetadataParams) error {
	_, err := q.db.Exec(ctx, updateProviderIdentityMetadata,
		arg.Email,
		arg.Now,
		arg.ID,
		arg.UserID,
	)
	return err
}
