// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :execrows
INSERT INTO app.sessions (id, user_id, kind, auth_method, token_hash, authenticated_at, created_at,
                          last_seen_at, idle_expires_at, absolute_expires_at)
SELECT $1, u.id, 'public', 'password', $2, $3, $3,
       $3, $4, $5
FROM app.users u JOIN app.password_credentials c ON c.user_id = u.id
WHERE u.id = $6 AND u.account_state = 'active' AND u.deleted_at IS NULL
  AND c.password_hash = $7
`

type CreateSessionParams struct {
	ID                pgtype.UUID
	TokenHash         []byte
	Now               pgtype.Timestamptz
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	UserID            pgtype.UUID
	VerifiedHash      string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.TokenHash,
		arg.Now,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.UserID,
		arg.VerifiedHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findActiveSessionByTokenHash = `-- name: FindActiveSessionByTokenHash :one
SELECT s.id, s.user_id, s.kind, s.authenticated_at, s.last_seen_at, s.absolute_expires_at
FROM app.sessions s JOIN app.users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.kind = 'public' AND s.revoked_at IS NULL
  AND s.idle_expires_at > $2 AND s.absolute_expires_at > $2
  AND u.account_state = 'active' AND u.deleted_at IS NULL
`

type FindActiveSessionByTokenHashParams struct {
	TokenHash []byte
	Now       pgtype.Timestamptz
}

type FindActiveSessionByTokenHashRow struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	Kind              string
	AuthenticatedAt   pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
}

func (q *Queries) FindActiveSessionByTokenHash(ctx context.Context, arg FindActiveSessionByTokenHashParams) (FindActiveSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, findActiveSessionByTokenHash, arg.TokenHash, arg.Now)
	var i FindActiveSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.AuthenticatedAt,
		&i.LastSeenAt,
		&i.AbsoluteExpiresAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE app.sessions SET revoked_at = $1
WHERE id = $2 AND user_id = $3 AND kind = 'public' AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	Now    pgtype.Timestamptz
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.Now, arg.ID, arg.UserID)
	return err
}

const touchSession = `-- name: TouchSession :execrows
UPDATE app.sessions s SET last_seen_at = $1,
    idle_expires_at = LEAST($2::timestamptz, s.absolute_expires_at)
WHERE s.id = $3 AND s.kind = 'public' AND s.revoked_at IS NULL
  AND s.idle_expires_at > $1 AND s.absolute_expires_at > $1
  AND s.last_seen_at <= $4
  AND EXISTS (SELECT 1 FROM app.users u WHERE u.id = s.user_id AND u.account_state = 'active' AND u.deleted_at IS NULL)
`

type TouchSessionParams struct {
	Now           pgtype.Timestamptz
	IdleExpiresAt pgtype.Timestamptz
	ID            pgtype.UUID
	TouchBefore   pgtype.Timestamptz
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchSession,
		arg.Now,
		arg.IdleExpiresAt,
		arg.ID,
		arg.TouchBefore,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
